services:
    mysql: # docker-compose exec -T mysql bash
        image: mysql:9.1.0
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: starshop_db
            MYSQL_USER: admin
            MYSQL_PASSWORD: admin
        volumes:
            - .docker/mysql/data:/var/lib/mysql
            - .docker/mysql/logs:/logs
        ports:
            - 3309:3306
    php: # docker-compose exec -T php bash
        build: './.docker/php'
        ports:
            - "8813:80"
        tty: true
        environment:
            PHP_IDE_CONFIG: "serverName=Starshop_Docker"
        volumes:
            - ./:/var/www/html/
            - ./.docker/php/logs/:/var/log/apache2/
            - ./.docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
            - ./.docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
            - ./.docker/php/conf.d/tzone.ini:/usr/local/etc/php/conf.d/tzone.ini
        extra_hosts:
            - "host.docker.internal:host-gateway"
        depends_on:
            - mysql
